base_gap_max: 5
base_gap_min: 1
base_skew_max: 4.0
base_skew_min: -4.0
bg_color:
- 250
- 250
- 250
box_color:
- 0
- 0
- 0
char_y_offset: 3
chinese_grid: false
chinese_grid_extra_left: 2
chinese_grid_extra_right: 2
chinese_grid_fill: true
chinese_grid_fill_to: 20
chinese_grid_max_padding: 12
chinese_grid_min_padding: 8
elastic_alpha: 3.6
elastic_sigma: 21
elastic_transform_prob: 0
font_size: 30
font_size_jittor_prob: 0.3
font_size_jittor_std: 2.0
font_weight_jittor_prob: 0.3
gap_mean: 0.0
gap_std_dev: 1.8
graph_grid_max_size: 20
graph_grid_min_size: 10
graph_grid: false
height: 64
limit_font_size: true
margin_bottom: 10
margin_left: 50
margin_right: 50
margin_top: 10
mask_with_ellipses_prob: 0
max_font_size: 35
min_font_size: 25
preload_all_fonts: true
random_color_prob: 0.3
random_crossout_prob: 0.001
random_font_size: true
random_margin: true
simplified_fonts_only: true
skew_mean: 1.0
skew_std_dev: 1.5
text_color:
- 255
- 0
- 0
