# Height
height: 64

# Margin
random_margin: true
margin_left: 50
margin_right: 50
margin_top: 10
margin_bottom: 10

# Font size
random_font_size: true
limit_font_size: true
font_size: 30
min_font_size: 25
max_font_size: 35

random_color_prob: 0.3
text_color: [255, 0, 0]
bg_color: [250, 250, 250]
box_color: [0, 0, 0]

graph_grid: false
graph_grid_size: 10
chinese_grid: false
chinese_grid_padding: 10

# Grids
chinese_grid_extra_left: 2
chinese_grid_extra_right: 2
chinese_grid_fill: true
chinese_grid_fill_to: 20

char_y_offset: 3

gap_mean: 0.0
gap_std_dev: 1.8
base_gap_min: 1
base_gap_max: 5

base_skew_min: -4.0
base_skew_max: 4.0
skew_mean: 1.0
skew_std_dev: 1.5

elastic_transform_prob: 0.4
elastic_alpha_ratio: 26
elastic_sigma_ratio: 0.22

simplified_fonts_only: true
